### ISSUE TITLE
Dot Notation does not work in version 1.7.14

### ISSUE THREAD

**Issue by momega** [mozilla/rhino#1161]
Rhino 1.7.14 breaks "dot notation" for accessing properties of the java Map instance (i.e. HashMap).
Here is the test to simulate the behavior. The following test passes in Rhino 1.7.13
```
@Test
void dotNotation() {
    var cx = org.mozilla.javascript.Context.enter();
    try {
        Scriptable scope = cx.initStandardObjects();
 
        // preparing my map
        Map<String, Object> map = new HashMap<>();
        map.put("id", "test");

        Object wrappedOut = org.mozilla.javascript.Context.javaToJS(map, scope);
        ScriptableObject.putProperty(scope, "map", wrappedOut);

        Object obj = cx.evaluateString(scope, "map.id", "", 1, null); // here is dot notation
        String str = (String) org.mozilla.javascript.Context.jsToJava(obj, String.class);
        assertEquals("test", str);
    } finally {
        org.mozilla.javascript.Context.exit();
    }
}
```

The result of the test in version 1.7.14 is the following
org.opentest4j.AssertionFailedError: 
Expected :test
Actual   :undefined

**Comment by tuchida** [comment]
ref. #820
This feature has been disabled by default for compatibility reasons, due to the following problems.
```js
var h = new java.util.HashMap();
h.put('a', 123);
h.a;  // 123.0
h.put('put', 123);
h.put; // 123.0
h.put('put', 123);
// js: "<stdin>", line 7: uncaught JavaScript runtime exception: TypeError: Cannot call property put in object {a=123.0, put=123.0}. It is not a function, it is "object".
//	at <stdin>:7
```
You can enable it in `Context.FEATURE_ENABLE_JAVA_MAP_ACCESS`. ref. https://github.com/mozilla/rhino/pull/836/files

**Comment by p-bakker** [comment]
I've updates the release notes for 1.7.14 with a '(Potential) Breaking Changes' section highlighting this behavior change in 1.7.14 compared to 1.7.13.

As this is an intentional change which is (now) documented and which can be controlled through the feature flag, I'm closing this issue

**Comment by p-bakker** [comment]
@tuchida from #820 I understand that Nashorn does support this in a way that doesn't cause issues and [here](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Context.java#L329) is says support is 'incomplete'.

Is there a case to complete the support so Context.FEATURE_ENABLE_JAVA_MAP_ACCESS could be enabled by default again?

Or was it deemed not feasible?

**Comment by tuchida** [comment]
It is probably feasible, but quite difficult.
In JavaScript, `Map` was added in ES6, so it is more convenient to use `java.util.Map` as `Map` instead of `Object`. ref. #846
```js
var javaMap = new java.util.HashMap({ abc: 123 });
var jsMap = new Map(javaMap);
// Can also be converted to Object
var jsObj = Object.fromEntries(javaMap);
```

**Comment by p-bakker** [comment]
Added a note about this in https://github.com/mozilla/rhino/projects/2#card-70815543 to discuss it for the v2.0.0

**Comment by tonygermano** [comment]
I think the best way to go about this in regard to `java.util.Map` is to implement a proxy wrapper class that translates all property access/writes to get/set on the underlying object. It could be made to work with both java Maps and Scriptables to give a common interface for both. Then you don't need to worry about when map keys conflict with java method names, which is the primary concern with using dot notation directly on Maps.

Since the Proxy would directly manipulate the java Map or Scriptable, holding on to a reference to the original object would let you return the updated original object. I think that is the main objection to conversion by shallow copy.

**Comment by tonygermano** [comment]
This does not currently work, but it's the general idea
```js
var map = new java.util.HashMap()

var wrapped = MapWrapper(map)
wrapped.a = 'A'
wrapped['b'] = 'B'
print(map.toString()) // {a=A, b=B}

var obj = {};
var wrapped = MapWrapper(obj)
wrapped.a = 'A'
wrapped['b'] = 'B'
print(JSON.stringify(obj)) // {"a":"A","b":"B"}
```

**Comment by tuchida** [comment]
There are other problems with this feature.
https://github.com/mozilla/rhino/blob/6c3a17faadf6adda6c37a9a48546fd245099b2d7/src/org/mozilla/javascript/Context.java#L335-L337
```js
map.put('1', 123);
map['1']; // Not found. This means `map[1]`.
```
In both Java's `java.util.Map` and JavaScript's `Map`, the type of key is not limited to strings. Can a JavaScript's `Object` really be called a Map?

**Comment by tberne** [comment]
Hey, guys. I'm replacing Nashorn with Rhino in a project and I'd like to have `Context.FEATURE_ENABLE_JAVA_MAP_ACCESS` enabled but I have no clue how to do so.
Given the JavaDoc of `org.mozilla.javascript.ContextFactory`, I suppose I should extend it and override `hasFeature(Context, int)`.
But it isn't clear to me where exactly I would use this context factory.
Nowadays, I use Nashorn via `javax.script.ScriptEngine` API.
So, to replace it with Rhino, I've just replaces the following line:

```java
return new ScriptEngineManager().getEngineByExtension("js");
```

with

```java
return new RhinoScriptEngineFactory().getScriptEngine();
```

And now I have no clue where I can instantiate the custom ContextFactory.

Thanks for your help.

**Comment by Lcify** [comment]
@tberne Try it, engine will auto load it.
```
public class CustomizedContextFactory extends ContextFactory {
    /**
     *
     * @param cx context
     * @param featureIndex feature index
     * @return ON or OFF
     */
    protected boolean hasFeature(Context cx, int featureIndex) {
        if (Context.FEATURE_ENABLE_JAVA_MAP_ACCESS == featureIndex) {
            return true;
        }
        return super.hasFeature(cx, featureIndex);
    }
}
```

**Comment by setteetrying** [comment]
> This does not currently work, but it's the general idea
> 
> var map = new java.util.HashMap()
> 
> var wrapped = MapWrapper(map)
> wrapped.put = 'A' // I believe this would throw an exception when called directly on a Map when the context flag is enabled
> wrapped['get'] = 'B'
> print(map.toString()) // {put=A, get=B}
> 
> var obj = {};
> var wrapped = MapWrapper(obj) // allow same semantics whether working with java.util.Map or Scriptable
> wrapped.put = 'A'
> wrapped['get'] = 'B'
> print(JSON.stringify(obj)) // {"put":"A","get":"B"}





https://openjs.space/questions/javascript-object-notation-is-a-standard-way-of-formatting
