### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown when compile long js

### ISSUE THREAD

**Issue by lalicw** [mozilla/rhino#529]
When we upgrade rhino from 1.7.R4 to 1.7.7.1, compilation error occurs for an exists long js which is ok in 1.7.R4.

the js has 2445 lines and 82277 characters, contains java importer, inner function and many comments. Before we upgrde the rhino, it's ok, we try to debug the source code and it's too complex to find out the root cause.

```java
java.lang.ArrayIndexOutOfBoundsException: -32748
        at org.mozilla.classfile.ClassFileWriter$StackMapTable.executeBlock:1731
        at org.mozilla.classfile.ClassFileWriter$StackMapTable.executeWorkList:1712
        at org.mozilla.classfile.ClassFileWriter$StackMapTable.verify:1626
        at org.mozilla.classfile.ClassFileWriter$StackMapTable.generate:1472
        at org.mozilla.classfile.ClassFileWriter.stopMethod:290
        at org.mozilla...optimizer.BodyCodegen.generateBodyCode:1292
        at org.mozilla...optimizer.Codegen.generateCode:306
        at org.mozilla...optimizer.Codegen.compileToClassFile:166
        at org.mozilla...optimizer.ClassCompiler.compileToClassFiles:155
        at com.huawei...script.JsCompiler.processSource:314
        at com.huawei...script.JsCompiler.compile:74
```
the js file structure is like this
```java
var javaImporter = JavaImporter();   

javaImporter.importPackage(Packages.java.lang);
javaImporter.importPackage(Packages.java.util); 
javaImporter.importClass(Packages.com.xxx.xxx.XXX);

with(javaImporter)
{
	function run(message)
	{
               function isEmpty(paramField)
               { 
   	               if("" ==paramField && null == paramField && "null" == String(paramField))
	              {
		              return true;
	              }
	             return false;
                }
                //...
         }

        function _isEmpty(value)
       {
            return value == "";
       }
      //...
}
```

JDK 1.8
Version:1.7.7.1

**Comment by lalicw** [comment]
We use the default CompilerEnvirons which mean we just new a CompilerEnvirons and don't set any attirbute.

**Comment by lalicw** [comment]
```java
   private void finalizeSuperBlockStarts() {
        if (GenerateStackMap) {
            for (int i = 0; i < itsExceptionTableTop; i++) {
                ExceptionTableEntry ete = itsExceptionTable[i];
               // it seems the getLabelPC return value more than 32767
                short handlerPC = (short) getLabelPC(ete.itsHandlerLabel);
                addSuperBlockStart(handlerPC);
            }
```
the tail values in itsLabelTable is as below:
![image](https://user-images.githubusercontent.com/3702970/55145231-53c9b280-517d-11e9-9878-427717d531b4.png)

**Comment by lalicw** [comment]
After i do some change as below in ClassFileWriter.java, it seems ok. but i'm not sure it's affect.
```java
short xxx = (short) getLabelPC(...)
```

to 

```java
int xxx = getLabelPC(...)
```

**Comment by rbri** [comment]
Did some history check, this was introduced with commit f81158c2ef9a9a62664c4ddf4614fe0284d02566 in 2010. For me it looks like some refactoring leftover because both involved methods are working with int's.

**Comment by lalicw** [comment]
> Did some history check, this was introduced with commit [f81158c](https://github.com/mozilla/rhino/commit/f81158c2ef9a9a62664c4ddf4614fe0284d02566) in 2010. For me it looks like some refactoring leftover because both involved methods are working with int's.

sorry, i'm not sure what you are talking about...
do you mean it's refactoring leftovers and will be fixed in the future release?
but when we use 1.7R4 it seems ok, it’s a strange result...

what if i need to fix it temporary?

**Comment by alexbrickwedde** [comment]
I also ran into this issue today. Will it be fixed?

**Comment by rbri** [comment]
Fix is on the way...
