### PR TITLE
[Experimental] Testing older android APIs

### PR DESCRIPTION
**Pull request by rPraml**
This is still in progress

### CODE REVIEW

**Comment by rPraml** [comment]
API 15 fails with: No emulator avaliable

API 21-23 fails with
```
java.lang.NoClassDefFoundError: org.mozilla.javascript.NativeError$$ExternalSyntheticLambda2
 	at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:147)
```
already reported in #1421

API 24-25 fails with
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
	at org.mozilla.javascript.NativeDate.<clinit>(NativeDate.java:2020)
``` 
a "regression" by https://github.com/mozilla/rhino/commit/3cfa4a00eb75384e5945b62bb38b37765d74c51d
(might me resolvable with https://stackoverflow.com/questions/66166211/an-alternative-to-datetimeformatter-in-android-api-21)

API 26 is the first working version (without desugaring!)

**Comment by rPraml** [comment]
Tests were done, with desugaring, we could achive minSDK 21 - only the varHandle Issue (#1785) is preventing us...
